#DOCKER FILE VERSION 1
FROM resin/%%RESIN_MACHINE_NAME%%-python
# Enable systemd
ENV INITSYSTEM on
#Install Docker on nuc
RUN apt-get -y update && apt-get install -y apt-transport-https ca-certificates
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
RUN touch /etc/apt/sources.list.d/docker.list
RUN echo "deb https://apt.dockerproject.org/repo debian-jessie main" > /etc/apt/sources.list.d/docker.list
RUN apt-get -y update
RUN apt-cache policy docker-engine
RUN sudo apt-get -y update
RUN sudo apt-get -y install docker-engine
RUN curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose
RUN chmod +x /usr/local/bin/docker-compose
